-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Symcrust.Types
open Aeneas.Std
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open symcrust

/- [symcrust::ntt::slice_to_sub_array]:
   Source: 'src/ntt.rs', lines 665:0-667:1 -/
axiom ntt.slice_to_sub_array
  (N : Usize) : Slice U8 → Usize → Result (Array U8 N)

/- [symcrust::ntt::SymCryptShake128Extract]:
   Source: 'src/ntt.rs', lines 760:0-767:1 -/
axiom ntt.SymCryptShake128Extract
  :
  Array U8 0#usize → Slice U8 → Bool → Result ((Array U8 0#usize) ×
    (Slice U8))

/- [symcrust::ntt::{symcrust::ntt::MATRIX<'a>}::swap]:
   Source: 'src/ntt.rs', lines 880:4-888:5 -/
axiom ntt.MATRIX.swap
  :
  ntt.MATRIX → Usize → Usize → Result (ntt.MATRIX × (ntt.MATRIX →
    ntt.MATRIX))

/- [symcrust::ntt::SymCryptMlKemPolyElementMulAndAccumulate_aux]:
   Source: 'src/ntt.rs', lines 918:0-928:1 -/
axiom ntt.SymCryptMlKemPolyElementMulAndAccumulate_aux
  :
  ntt.MATRIX → Usize → Usize → Usize → Array U16 256#usize → Array
    U32 256#usize → Result (ntt.MATRIX × (ntt.MATRIX → ntt.MATRIX) ×
    (Array U32 256#usize))

/- [symcrust::misc::main]:
   Source: 'src/misc.rs', lines 8:0-21:1 -/
axiom misc.main : Result Unit

