-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: type definitions
import Aeneas
open Aeneas.Std
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace symcrust

/- [symcrust::ntt::MATRIX]
   Source: 'src/ntt.rs', lines 82:0-85:1 -/
structure ntt.MATRIX where
  nRows : Usize
  apPolyElements : Array (Array U16 256#usize) 16#usize

/- [symcrust::ntt::INTERNAL_PARAMS]
   Source: 'src/ntt.rs', lines 93:0-110:1 -/
structure ntt.INTERNAL_PARAMS where
  params : U32
  cbPolyElement : U32
  cbVector : U32
  cbMatrix : U32
  nRows : U8
  nEta1 : U8
  nEta2 : U8
  nBitsOfU : U8
  nBitsOfV : U8

/- [symcrust::ntt::KEY]
   Source: 'src/ntt.rs', lines 112:0-141:1 -/
structure ntt.KEY where
  fAlgorithmInfo : U32
  params : ntt.INTERNAL_PARAMS
  cbTotalSize : U32
  hasPrivateSeed : Bool
  hasPrivateKey : Bool
  privateSeed : Array U8 32#usize
  privateRandom : Array U8 32#usize
  publicSeed : Array U8 32#usize
  pmAtranspose : ntt.MATRIX
  pvt : Slice (Array U16 256#usize)
  pvs : Slice (Array U16 256#usize)
  encodedT : Array U8 1536#usize
  encapsKeyHash : Array U8 32#usize

/- [symcrust::ntt::INTERNAL_COMPUTATION_TEMPORARIES]
   Source: 'src/ntt.rs', lines 177:0-185:1 -/
structure ntt.INTERNAL_COMPUTATION_TEMPORARIES where
  abVectorBuffer0 : Array (Array U16 256#usize) 4#usize
  abVectorBuffer1 : Array (Array U16 256#usize) 4#usize
  abPolyElementBuffer0 : Array U16 256#usize
  abPolyElementBuffer1 : Array U16 256#usize
  abPolyElementAccumulatorBuffer : Array U32 256#usize

/- [symcrust::ntt::MLKEM_ERROR]
   Source: 'src/ntt.rs', lines 705:0-705:43 -/
inductive ntt.MLKEM_ERROR where
| NO_ERROR : ntt.MLKEM_ERROR
| INVALID_BLOB : ntt.MLKEM_ERROR

/- [symcrust::misc::Temporaries]
   Source: 'src/misc.rs', lines 2:0-5:1 -/
structure misc.Temporaries where
  data1 : Array U8 16#usize
  data2 : Array U8 16#usize

end symcrust
