/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --log Phase2.7
  F* version: <unknown>
  KaRaMeL version: fd20524c
 */

#ifndef __Eurydice_H
#define __Eurydice_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "eurydice_glue.h"

/**
A monomorphic instance of core.ops.range.Range
with types size_t

*/
typedef struct core_ops_range_Range_08_s
{
  size_t start;
  size_t end;
}
core_ops_range_Range_08;

#if defined(__cplusplus)
}
#endif

#define __Eurydice_H_DEFINED
#endif
