/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 2e1ab5b9
 */

#include "internal/symcrust_common.h"

void symcrust_common_init(void)
{
  symcrust_common_SymCryptModuleInit(103U, 8U);
}

symcrust_common_Error symcrust_common_random(Eurydice_slice dst)
{
  /* #[cfg(not(feature = "dynamic"))]
    unsafe {
        SymCryptCallbackRandom(dst.as_mut_ptr(), dst.len())
    }
    #[cfg(feature = "dynamic")] */
  uint8_t *uu____0 = core_slice___Slice_T___as_mut_ptr(dst, uint8_t, uint8_t *);
  symcrust_common_SymCryptRandom(uu____0, Eurydice_slice_len(dst, uint8_t));
  return symcrust_common_Error_NoError;
}

void symcrust_common_wipe(uint8_t *pb_data, size_t cb_data)
{
  symcrust_common_SymCryptWipe(pb_data, cb_data);
}

/**
This function found in impl {core::cmp::PartialEq<symcrust::common::Error> for symcrust::common::Error}
*/
bool symcrust_common_eq_41(symcrust_common_Error *self, symcrust_common_Error *other)
{
  ptrdiff_t __self_discr = (ptrdiff_t)self[0U];
  ptrdiff_t __arg1_discr = (ptrdiff_t)other[0U];
  return __self_discr == __arg1_discr;
}

/**
This function found in impl {core::fmt::Debug for symcrust::common::Error}
*/
inline core_result_Result_10
symcrust_common_fmt_b9(symcrust_common_Error *self, core_fmt_Formatter *f)
{
  core_fmt_Formatter *uu____0 = f;
  Eurydice_str uu____1;
  switch (self[0U])
  {
    case symcrust_common_Error_NoError:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "NoError", .len = (size_t)7U });
        break;
      }
    case symcrust_common_Error_Unused:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "Unused", .len = (size_t)6U });
        break;
      }
    case symcrust_common_Error_WrongKeySize:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "WrongKeySize", .len = (size_t)12U });
        break;
      }
    case symcrust_common_Error_WrongBlockSize:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "WrongBlockSize", .len = (size_t)14U });
        break;
      }
    case symcrust_common_Error_WrongDataSize:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "WrongDataSize", .len = (size_t)13U });
        break;
      }
    case symcrust_common_Error_WrongNonceSize:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "WrongNonceSize", .len = (size_t)14U });
        break;
      }
    case symcrust_common_Error_WrongTagSize:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "WrongTagSize", .len = (size_t)12U });
        break;
      }
    case symcrust_common_Error_WrongIterationCount:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "WrongIterationCount", .len = (size_t)19U });
        break;
      }
    case symcrust_common_Error_AuthenticationFailure:
      {
        uu____1 =
          (KRML_CLITERAL(Eurydice_str){ .data = "AuthenticationFailure", .len = (size_t)21U });
        break;
      }
    case symcrust_common_Error_ExternalFailure:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "ExternalFailure", .len = (size_t)15U });
        break;
      }
    case symcrust_common_Error_FipsFailure:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "FipsFailure", .len = (size_t)11U });
        break;
      }
    case symcrust_common_Error_HardwareFailure:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "HardwareFailure", .len = (size_t)15U });
        break;
      }
    case symcrust_common_Error_NotImplemented:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "NotImplemented", .len = (size_t)14U });
        break;
      }
    case symcrust_common_Error_InvalidBlob:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "InvalidBlob", .len = (size_t)11U });
        break;
      }
    case symcrust_common_Error_BufferTooSmall:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "BufferTooSmall", .len = (size_t)14U });
        break;
      }
    case symcrust_common_Error_InvalidArgument:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "InvalidArgument", .len = (size_t)15U });
        break;
      }
    case symcrust_common_Error_MemoryAllocationFailure:
      {
        uu____1 =
          (KRML_CLITERAL(Eurydice_str){ .data = "MemoryAllocationFailure", .len = (size_t)23U });
        break;
      }
    case symcrust_common_Error_SignatureVerificationFailure:
      {
        uu____1 =
          (
            KRML_CLITERAL(Eurydice_str){
              .data = "SignatureVerificationFailure",
              .len = (size_t)28U
            }
          );
        break;
      }
    case symcrust_common_Error_IncompatibleFormat:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "IncompatibleFormat", .len = (size_t)18U });
        break;
      }
    case symcrust_common_Error_ValueTooLarge:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "ValueTooLarge", .len = (size_t)13U });
        break;
      }
    case symcrust_common_Error_SessionReplayFailure:
      {
        uu____1 =
          (KRML_CLITERAL(Eurydice_str){ .data = "SessionReplayFailure", .len = (size_t)20U });
        break;
      }
    case symcrust_common_Error_HbsNoOtsKeysLeft:
      {
        uu____1 = (KRML_CLITERAL(Eurydice_str){ .data = "HbsNoOtsKeysLeft", .len = (size_t)16U });
        break;
      }
    case symcrust_common_Error_HbsPublicRootMismatch:
      {
        uu____1 =
          (KRML_CLITERAL(Eurydice_str){ .data = "HbsPublicRootMismatch", .len = (size_t)21U });
        break;
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
  return core_fmt__core__fmt__Formatter__a___write_str(uu____0, uu____1);
}

