/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 52173e05
 */

#include "internal/symcrust_common.h"

extern void symcrust_common_SymCryptRandom(uint8_t *x0, size_t x1);

extern void symcrust_common_SymCryptWipe(uint8_t *x0, size_t x1);

symcrust_common_Error symcrust_common_random(Eurydice_slice dst)
{
  uint8_t
  *uu____0 =
    core_slice___Slice_T___as_mut_ptr(/* #[cfg(not(feature = "dynamic"))] unsafe { SymCryptCallbackRandom(dst.as_mut_ptr(), dst.len()) } #[cfg(feature = "dynamic")] */
        dst
      ,
      uint8_t,
      uint8_t *);
  symcrust_common_SymCryptRandom(uu____0, Eurydice_slice_len(dst, uint8_t));
  return symcrust_common_Error_NoError;
}

void symcrust_common_wipe(uint8_t *pb_data, size_t cb_data)
{
  symcrust_common_SymCryptWipe(pb_data, cb_data);
}

/**
This function found in impl {(core::cmp::PartialEq<symcrust::common::Error> for symcrust::common::Error)#1}
*/
bool symcrust_common_eq_3d(symcrust_common_Error *self, symcrust_common_Error *other)
{
  ptrdiff_t __self_discr;
  symcrust_common_Error scrut0 = self[0U];
  if (scrut0 == symcrust_common_Error_NoError)
  {
    __self_discr = (ptrdiff_t)0;
  }
  else if (scrut0 == symcrust_common_Error_Unused)
  {
    __self_discr = (ptrdiff_t)32768;
  }
  else if (scrut0 == symcrust_common_Error_WrongKeySize)
  {
    __self_discr = (ptrdiff_t)32769;
  }
  else if (scrut0 == symcrust_common_Error_WrongBlockSize)
  {
    __self_discr = (ptrdiff_t)32770;
  }
  else if (scrut0 == symcrust_common_Error_WrongDataSize)
  {
    __self_discr = (ptrdiff_t)32771;
  }
  else if (scrut0 == symcrust_common_Error_WrongNonceSize)
  {
    __self_discr = (ptrdiff_t)32772;
  }
  else if (scrut0 == symcrust_common_Error_WrongTagSize)
  {
    __self_discr = (ptrdiff_t)32773;
  }
  else if (scrut0 == symcrust_common_Error_WrongIterationCount)
  {
    __self_discr = (ptrdiff_t)32774;
  }
  else if (scrut0 == symcrust_common_Error_AuthenticationFailure)
  {
    __self_discr = (ptrdiff_t)32775;
  }
  else if (scrut0 == symcrust_common_Error_ExternalFailure)
  {
    __self_discr = (ptrdiff_t)32776;
  }
  else if (scrut0 == symcrust_common_Error_FipsFailure)
  {
    __self_discr = (ptrdiff_t)32777;
  }
  else if (scrut0 == symcrust_common_Error_HardwareFailure)
  {
    __self_discr = (ptrdiff_t)32778;
  }
  else if (scrut0 == symcrust_common_Error_NotImplemented)
  {
    __self_discr = (ptrdiff_t)32779;
  }
  else if (scrut0 == symcrust_common_Error_InvalidBlob)
  {
    __self_discr = (ptrdiff_t)32780;
  }
  else if (scrut0 == symcrust_common_Error_BufferTooSmall)
  {
    __self_discr = (ptrdiff_t)32781;
  }
  else if (scrut0 == symcrust_common_Error_InvalidArgument)
  {
    __self_discr = (ptrdiff_t)32782;
  }
  else if (scrut0 == symcrust_common_Error_MemoryAllocationFailure)
  {
    __self_discr = (ptrdiff_t)32783;
  }
  else if (scrut0 == symcrust_common_Error_SignatureVerificationFailure)
  {
    __self_discr = (ptrdiff_t)32784;
  }
  else if (scrut0 == symcrust_common_Error_IncompatibleFormat)
  {
    __self_discr = (ptrdiff_t)32785;
  }
  else if (scrut0 == symcrust_common_Error_ValueTooLarge)
  {
    __self_discr = (ptrdiff_t)32786;
  }
  else if (scrut0 == symcrust_common_Error_SessionReplayFailure)
  {
    __self_discr = (ptrdiff_t)32787;
  }
  else if (scrut0 == symcrust_common_Error_HbsNoOtsKeysLeft)
  {
    __self_discr = (ptrdiff_t)32788;
  }
  else
  {
    __self_discr = (ptrdiff_t)32789;
  }
  ptrdiff_t __arg1_discr;
  symcrust_common_Error scrut = other[0U];
  if (scrut == symcrust_common_Error_NoError)
  {
    __arg1_discr = (ptrdiff_t)0;
  }
  else if (scrut == symcrust_common_Error_Unused)
  {
    __arg1_discr = (ptrdiff_t)32768;
  }
  else if (scrut == symcrust_common_Error_WrongKeySize)
  {
    __arg1_discr = (ptrdiff_t)32769;
  }
  else if (scrut == symcrust_common_Error_WrongBlockSize)
  {
    __arg1_discr = (ptrdiff_t)32770;
  }
  else if (scrut == symcrust_common_Error_WrongDataSize)
  {
    __arg1_discr = (ptrdiff_t)32771;
  }
  else if (scrut == symcrust_common_Error_WrongNonceSize)
  {
    __arg1_discr = (ptrdiff_t)32772;
  }
  else if (scrut == symcrust_common_Error_WrongTagSize)
  {
    __arg1_discr = (ptrdiff_t)32773;
  }
  else if (scrut == symcrust_common_Error_WrongIterationCount)
  {
    __arg1_discr = (ptrdiff_t)32774;
  }
  else if (scrut == symcrust_common_Error_AuthenticationFailure)
  {
    __arg1_discr = (ptrdiff_t)32775;
  }
  else if (scrut == symcrust_common_Error_ExternalFailure)
  {
    __arg1_discr = (ptrdiff_t)32776;
  }
  else if (scrut == symcrust_common_Error_FipsFailure)
  {
    __arg1_discr = (ptrdiff_t)32777;
  }
  else if (scrut == symcrust_common_Error_HardwareFailure)
  {
    __arg1_discr = (ptrdiff_t)32778;
  }
  else if (scrut == symcrust_common_Error_NotImplemented)
  {
    __arg1_discr = (ptrdiff_t)32779;
  }
  else if (scrut == symcrust_common_Error_InvalidBlob)
  {
    __arg1_discr = (ptrdiff_t)32780;
  }
  else if (scrut == symcrust_common_Error_BufferTooSmall)
  {
    __arg1_discr = (ptrdiff_t)32781;
  }
  else if (scrut == symcrust_common_Error_InvalidArgument)
  {
    __arg1_discr = (ptrdiff_t)32782;
  }
  else if (scrut == symcrust_common_Error_MemoryAllocationFailure)
  {
    __arg1_discr = (ptrdiff_t)32783;
  }
  else if (scrut == symcrust_common_Error_SignatureVerificationFailure)
  {
    __arg1_discr = (ptrdiff_t)32784;
  }
  else if (scrut == symcrust_common_Error_IncompatibleFormat)
  {
    __arg1_discr = (ptrdiff_t)32785;
  }
  else if (scrut == symcrust_common_Error_ValueTooLarge)
  {
    __arg1_discr = (ptrdiff_t)32786;
  }
  else if (scrut == symcrust_common_Error_SessionReplayFailure)
  {
    __arg1_discr = (ptrdiff_t)32787;
  }
  else if (scrut == symcrust_common_Error_HbsNoOtsKeysLeft)
  {
    __arg1_discr = (ptrdiff_t)32788;
  }
  else
  {
    __arg1_discr = (ptrdiff_t)32789;
  }
  return __self_discr == __arg1_discr;
}

