/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 67529ac3
 */

#ifndef __symcrust_common_H
#define __symcrust_common_H

#include "eurydice_glue.h"


#if defined(__cplusplus)
extern "C" {
#endif

#define core_result_Ok 0
#define core_result_Err 1

typedef uint8_t core_result_Result_10;

#define symcrust_common_Error_NoError 0
#define symcrust_common_Error_Unused 32768
#define symcrust_common_Error_WrongKeySize 32769
#define symcrust_common_Error_WrongBlockSize 32770
#define symcrust_common_Error_WrongDataSize 32771
#define symcrust_common_Error_WrongNonceSize 32772
#define symcrust_common_Error_WrongTagSize 32773
#define symcrust_common_Error_WrongIterationCount 32774
#define symcrust_common_Error_AuthenticationFailure 32775
#define symcrust_common_Error_ExternalFailure 32776
#define symcrust_common_Error_FipsFailure 32777
#define symcrust_common_Error_HardwareFailure 32778
#define symcrust_common_Error_NotImplemented 32779
#define symcrust_common_Error_InvalidBlob 32780
#define symcrust_common_Error_BufferTooSmall 32781
#define symcrust_common_Error_InvalidArgument 32782
#define symcrust_common_Error_MemoryAllocationFailure 32783
#define symcrust_common_Error_SignatureVerificationFailure 32784
#define symcrust_common_Error_IncompatibleFormat 32785
#define symcrust_common_Error_ValueTooLarge 32786
#define symcrust_common_Error_SessionReplayFailure 32787
#define symcrust_common_Error_HbsNoOtsKeysLeft 32788
#define symcrust_common_Error_HbsPublicRootMismatch 32789

typedef uint16_t symcrust_common_Error;

#if defined(__cplusplus)
}
#endif

#define __symcrust_common_H_DEFINED
#endif
