/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 67529ac3
 */

#ifndef __symcrust_mlkem_H
#define __symcrust_mlkem_H

#include "eurydice_glue.h"


#if defined(__cplusplus)
extern "C" {
#endif

#include "hash_shims.h"

#include "symcrust_common.h"

#define symcrust_key_Format_PrivateSeed 1
#define symcrust_key_Format_DecapsulationKey 2
#define symcrust_key_Format_EncapsulationKey 3

typedef uint8_t symcrust_key_Format;

#define symcrust_key_Params_MlKem512 1
#define symcrust_key_Params_MlKem768 2
#define symcrust_key_Params_MlKem1024 3

typedef uint8_t symcrust_key_Params;

typedef struct symcrust_key_InternalParams_s
{
  symcrust_key_Params params;
  uint8_t n_rows;
  uint8_t n_eta1;
  uint8_t n_eta2;
  uint8_t n_bits_of_u;
  uint8_t n_bits_of_v;
}
symcrust_key_InternalParams;

#define SYMCRUST_KEY_INTERNAL_PARAMS_ML_KEM1024 ((KRML_CLITERAL(symcrust_key_InternalParams){ .params = symcrust_key_Params_MlKem1024, .n_rows = 4U, .n_eta1 = 2U, .n_eta2 = 2U, .n_bits_of_u = 11U, .n_bits_of_v = 5U }))

#define SYMCRUST_KEY_INTERNAL_PARAMS_ML_KEM512 ((KRML_CLITERAL(symcrust_key_InternalParams){ .params = symcrust_key_Params_MlKem512, .n_rows = 2U, .n_eta1 = 3U, .n_eta2 = 2U, .n_bits_of_u = 10U, .n_bits_of_v = 4U }))

#define SYMCRUST_KEY_INTERNAL_PARAMS_ML_KEM768 ((KRML_CLITERAL(symcrust_key_InternalParams){ .params = symcrust_key_Params_MlKem768, .n_rows = 3U, .n_eta1 = 2U, .n_eta2 = 2U, .n_bits_of_u = 10U, .n_bits_of_v = 4U }))

#define SYMCRUST_KEY_KEY_MAX_SIZEOF_ENCODED_T ((size_t)1536U)

typedef struct symcrust_key_PreKey2Header_s
{
  uint32_t algorithm_info;
  symcrust_key_InternalParams params;
  bool has_private_seed;
  bool has_private_key;
  uint8_t private_seed[32U];
  uint8_t private_random[32U];
  uint8_t public_seed[32U];
  uint8_t encoded_t[1536U];
  uint8_t encaps_key_hash[32U];
  size_t n_rows;
}
symcrust_key_PreKey2Header;

typedef struct symcrust_key_Key_s
{
  symcrust_key_PreKey2Header header;
  Eurydice_derefed_slice data;
}
symcrust_key_Key;

typedef symcrust_key_Key symcrust_key_Key2;

#define SYMCRUST_KEY_MLWE_POLYNOMIAL_COEFFICIENTS ((size_t)256U)

typedef Eurydice_derefed_slice symcrust_key_Matrix2;

extern const uint16_t symcrust_key_POLYELEMENT_ZERO[256U];

typedef uint16_t symcrust_key_PolyElement[256U];

typedef Eurydice_derefed_slice symcrust_key_Vector;

symcrust_key_InternalParams
symcrust_key_get_internal_params_from_params(symcrust_key_Params params);

/**
A monomorphic instance of Eurydice.dst
with types symcrust_key_PreKey2 Eurydice_derefed_slice uint16_t[256size_t]

*/
typedef struct Eurydice_dst_8c_s
{
  symcrust_key_Key *ptr;
  size_t len;
}
Eurydice_dst_8c;

/**
A monomorphic instance of core.result.Result
with types Eurydice_dst symcrust_key_PreKey2 Eurydice_derefed_slice uint16_t[256size_t], symcrust_common_Error

*/
typedef struct core_result_Result_67_s
{
  core_result_Result_10 tag;
  union {
    Eurydice_dst_8c case_Ok;
    symcrust_common_Error case_Err;
  }
  val;
}
core_result_Result_67;

/**
A monomorphic instance of symcrust.key.PreKey2
with types uint16_t[256size_t][8size_t]

*/
typedef struct symcrust_key_PreKey2_51_s
{
  symcrust_key_PreKey2Header header;
  uint16_t data[8U][256U];
}
symcrust_key_PreKey2_51;

/**
A monomorphic instance of symcrust.key.PreKey2
with types uint16_t[256size_t][15size_t]

*/
typedef struct symcrust_key_PreKey2_7d_s
{
  symcrust_key_PreKey2Header header;
  uint16_t data[15U][256U];
}
symcrust_key_PreKey2_7d;

/**
A monomorphic instance of symcrust.key.PreKey2
with types uint16_t[256size_t][24size_t]

*/
typedef struct symcrust_key_PreKey2_76_s
{
  symcrust_key_PreKey2Header header;
  uint16_t data[24U][256U];
}
symcrust_key_PreKey2_76;

core_result_Result_67 symcrust_key_key_allocate2(symcrust_key_Params params);

core_result_Result_67 symcrust_key_key_allocate(symcrust_key_Params params);

/**
This function found in impl {core::clone::Clone for symcrust::key::Params}
*/
symcrust_key_Params symcrust_key_clone_61(symcrust_key_Params *self);

/**
This function found in impl {core::cmp::PartialEq<symcrust::key::Params> for symcrust::key::Params}
*/
bool symcrust_key_eq_d5(symcrust_key_Params *self, symcrust_key_Params *other);

extern bool
symcrust_key__core__cmp__PartialEq_symcrust__key__Params__for_symcrust__key__Params__ne(
  symcrust_key_Params *x0,
  symcrust_key_Params *x1
);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
size_t symcrust_key_matrix_len_fd(Eurydice_dst_8c self);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice symcrust_key_atranspose_fd(Eurydice_dst_8c self);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice symcrust_key_atranspose_mut_fd(Eurydice_dst_8c self);

typedef struct Eurydice_slice_uint16_t_256size_t__x3_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
  Eurydice_slice thd;
}
Eurydice_slice_uint16_t_256size_t__x3;

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice_uint16_t_256size_t__x3 symcrust_key_ats_mut_fd(Eurydice_dst_8c self);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice symcrust_key_s_fd(Eurydice_dst_8c self);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice symcrust_key_s_mut_fd(Eurydice_dst_8c self);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice symcrust_key_t_fd(Eurydice_dst_8c self);

/**
A monomorphic instance of K.
with types Eurydice_slice uint16_t[256size_t],  uint8_t*

*/
typedef struct tuple_48_s
{
  Eurydice_slice fst;
  uint8_t *snd;
}
tuple_48;

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
tuple_48 symcrust_key_t_encoded_t_mut_fd(Eurydice_dst_8c self);

/**
This function found in impl {symcrust::key::PreKey2<@Slice<@Array<u16, 256: usize>>>}
*/
Eurydice_slice symcrust_key_t_mut_fd(Eurydice_dst_8c self);

#define SYMCRUST_MLKEM_CIPHERTEXT_SIZE_MLKEM1024 ((size_t)1568U)

#define SYMCRUST_MLKEM_CIPHERTEXT_SIZE_MLKEM512 ((size_t)768U)

#define SYMCRUST_MLKEM_CIPHERTEXT_SIZE_MLKEM768 ((size_t)1088U)

#define SYMCRUST_MLKEM_FLAG_KEY_MINIMAL_VALIDATION (512U)

#define SYMCRUST_MLKEM_FLAG_KEY_NO_FIPS (256U)

#define SYMCRUST_MLKEM_SIZEOF_AGREED_SECRET ((size_t)32U)

#define SYMCRUST_MLKEM_SIZEOF_ENCAPS_RANDOM ((size_t)32U)

#define SYMCRUST_MLKEM_SIZEOF_FORMAT_PRIVATE_SEED ((size_t)2U * (size_t)32U)

#define SYMCRUST_MLKEM_SIZEOF_MAX_CIPHERTEXT ((size_t)1568U)

typedef struct symcrust_ntt_InternalComputationTemporaries_s
{
  uint16_t ab_vector_buffer0[4U][256U];
  uint16_t ab_vector_buffer1[4U][256U];
  uint16_t ab_poly_element_buffer0[256U];
  uint16_t ab_poly_element_buffer1[256U];
  uint32_t ab_poly_element_accumulator_buffer[256U];
  symcrust_hash_HashState hash_state0;
  symcrust_hash_HashState hash_state1;
}
symcrust_ntt_InternalComputationTemporaries;

symcrust_common_Error
symcrust_mlkem_encapsulate_internal(
  Eurydice_dst_8c pk_mlkem_key,
  Eurydice_slice pb_agreed_secret,
  Eurydice_slice pb_ciphertext,
  uint8_t *pb_random,
  symcrust_ntt_InternalComputationTemporaries *p_comp_temps
);

symcrust_common_Error
symcrust_mlkem_decapsulate(
  Eurydice_dst_8c pk_mlkem_key,
  Eurydice_slice pb_ciphertext,
  Eurydice_slice pb_agreed_secret
);

symcrust_common_Error
symcrust_mlkem_encapsulate_ex(
  Eurydice_dst_8c pk_mlkem_key,
  Eurydice_slice pb_random,
  Eurydice_slice pb_agreed_secret,
  Eurydice_slice pb_ciphertext
);

symcrust_common_Error
symcrust_mlkem_encapsulate(
  Eurydice_dst_8c pk_mlkem_key,
  Eurydice_slice pb_agreed_secret,
  Eurydice_slice pb_ciphertext
);

size_t symcrust_mlkem_sizeof_encoded_uncompressed_vector(size_t _n_rows);

void
symcrust_mlkem_key_compute_encapsulation_key_hash(
  Eurydice_dst_8c pk_mlkem_key,
  symcrust_ntt_InternalComputationTemporaries *p_comp_temps
);

void
symcrust_mlkem_key_expand_public_matrix_from_public_seed(
  Eurydice_dst_8c pk_mlkem_key,
  symcrust_ntt_InternalComputationTemporaries *p_comp_temps
);

void
symcrust_mlkem_key_expand_from_private_seed(
  Eurydice_dst_8c pk_mlkem_key,
  symcrust_ntt_InternalComputationTemporaries *p_comp_temps
);

size_t symcrust_mlkem_sizeof_format_decapsulation_key(size_t _n_rows);

size_t symcrust_mlkem_sizeof_format_encapsulation_key(size_t _n_rows);

symcrust_common_Error
symcrust_mlkem_key_set_value(
  Eurydice_slice pb_src,
  symcrust_key_Format format,
  uint32_t flags,
  Eurydice_dst_8c pk_mlkem_key
);

symcrust_common_Error
symcrust_mlkem_key_generate(Eurydice_dst_8c pk_mlkem_key, uint32_t flags);

symcrust_common_Error
symcrust_mlkem_key_get_value(
  Eurydice_dst_8c pk_mlkem_key,
  Eurydice_slice pb_dst,
  symcrust_key_Format format,
  uint32_t _flags
);

size_t symcrust_mlkem_sizeof_ciphertext_from_params(symcrust_key_Params params);

size_t
symcrust_mlkem_sizeof_key_format_from_params(
  symcrust_key_Params params,
  symcrust_key_Format format
);

#if defined(__cplusplus)
}
#endif

#define __symcrust_mlkem_H_DEFINED
#endif
