/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 734ff7e1
 */

#ifndef __internal_symcrust_mlkem_H
#define __internal_symcrust_mlkem_H

#include "eurydice_glue.h"


#if defined(__cplusplus)
extern "C" {
#endif

#include "internal/symcrust_hash.h"
#include "internal/symcrust_common.h"
#include "symcrust_hash.h"
#include "symcrust_common.h"
#include "../symcrust_mlkem.h"

/**
A monomorphic instance of Eurydice.arr
with types Eurydice_str
with const generics
- $1size_t
*/
typedef struct Eurydice_arr_7d_s { Eurydice_str data[1U]; } Eurydice_arr_7d;

/**
A monomorphic instance of core.result.Result
with types core_convert_Infallible, symcrust_common_Error

*/
typedef struct core_result_Result_b5_s
{
  core_result_Result_10 tag;
  union {
    core_convert_Infallible case_Ok;
    symcrust_common_Error case_Err;
  }
  val;
}
core_result_Result_b5;

/**
This function found in impl {core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, symcrust::common::Error>> for symcrust::common::Error}
*/
symcrust_common_Error symcrust_error_from_residual_54(core_result_Result_b5 r);

/**
A monomorphic instance of symcrust.common.wipe_slice
with types uint32_t

*/
void symcrust_common_wipe_slice_df(Eurydice_slice pb_dst);

/**
A monomorphic instance of symcrust.common.wipe_slice
with types uint16_t

*/
void symcrust_common_wipe_slice_de(Eurydice_slice pb_dst);

/**
A monomorphic instance of core.result.Result
with types  Eurydice_arr uint8_t[[$64size_t]]*, core_array_TryFromSliceError

*/
typedef struct core_result_Result_20_s
{
  core_result_Result_10 tag;
  union {
    Eurydice_arr_06 *case_Ok;
    core_array_TryFromSliceError case_Err;
  }
  val;
}
core_result_Result_20;

/**
A monomorphic instance of Eurydice.arr
with types uint8_t
with const generics
- $193size_t
*/
typedef struct Eurydice_arr_73_s { uint8_t data[193U]; } Eurydice_arr_73;

/**
A monomorphic instance of core.result.Result
with types  symcrust_ntt_InternalComputationTemporaries*, ()

*/
typedef struct core_result_Result_80_s
{
  core_result_Result_10 tag;
  symcrust_ntt_InternalComputationTemporaries *f0;
}
core_result_Result_80;

typedef struct Eurydice_slice_uint8_t_x2_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
}
Eurydice_slice_uint8_t_x2;

/**
A monomorphic instance of core.result.Result
with types  Eurydice_arr uint8_t[[$32size_t]]*, core_array_TryFromSliceError

*/
typedef struct core_result_Result_30_s
{
  core_result_Result_10 tag;
  union {
    Eurydice_arr_60 *case_Ok;
    core_array_TryFromSliceError case_Err;
  }
  val;
}
core_result_Result_30;

/**
A monomorphic instance of Eurydice.arr
with types uint8_t
with const generics
- $24size_t
*/
typedef struct Eurydice_arr_6d_s { uint8_t data[24U]; } Eurydice_arr_6d;

typedef struct Eurydice_slice_Eurydice_arr_uint16_t___256size_t___x2_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
}
Eurydice_slice_Eurydice_arr_uint16_t___256size_t___x2;

/**
A monomorphic instance of symcrust.common.wipe_slice
with types uint8_t

*/
void symcrust_common_wipe_slice_90(Eurydice_slice pb_dst);

#if defined(__cplusplus)
}
#endif

#define __internal_symcrust_mlkem_H_DEFINED
#endif
