/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 52173e05
 */

#ifndef __internal_symcrust_mlkem_H
#define __internal_symcrust_mlkem_H

#include "eurydice_glue.h"


#if defined(__cplusplus)
extern "C" {
#endif

#include "../symcrust_mlkem.h"

typedef struct Eurydice_slice_uint16_t_256size_t__x2_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
}
Eurydice_slice_uint16_t_256size_t__x2;

/**
A monomorphic instance of core.result.Result
with types  uint8_t*, core_array_TryFromSliceError

*/
typedef struct core_result_Result_a0_s
{
  core_result_Result_67_tags tag;
  union {
    uint8_t *case_Ok;
    core_array_TryFromSliceError case_Err;
  }
  val;
}
core_result_Result_a0;

typedef struct Eurydice_slice_uint8_t_x2_s
{
  Eurydice_slice fst;
  Eurydice_slice snd;
}
Eurydice_slice_uint8_t_x2;

#if defined(__cplusplus)
}
#endif

#define __internal_symcrust_mlkem_H_DEFINED
#endif
