/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: /Users/jonathan/Code/eurydice/eurydice symcrust.llbc --output c/ -fcomments --config c.yaml
  F* version: <unknown>
  KaRaMeL version: 2e1ab5b9
 */

#ifndef __internal_symcrust_ffi_H
#define __internal_symcrust_ffi_H

#include "eurydice_glue.h"


#if defined(__cplusplus)
extern "C" {
#endif

#include "internal/symcrust_common.h"
#include "../symcrust_ffi.h"

/**
This function found in impl {core::fmt::Arguments<'a>}
*/
/**
A monomorphic instance of core.fmt.rt.new_const_21
with const generics
- N= 1
*/
core_fmt_Arguments core_fmt_rt_new_const_21_74(Eurydice_str *pieces);

/**
This function found in impl {core::convert::TryInto<U, Clause2_Error> for T}
*/
/**
A monomorphic instance of core.convert.try_into_32
with types int32_t, symcrust_key_Params, symcrust_common_Error
with const generics

*/
static inline core_result_Result_fa core_convert_try_into_32_0a(int32_t self)
{
  return symcrust_ffi_try_from_1e(self);
}

/**
This function found in impl {core::convert::TryInto<U, Clause2_Error> for T}
*/
/**
A monomorphic instance of core.convert.try_into_32
with types int32_t, symcrust_key_Format, symcrust_common_Error
with const generics

*/
static inline core_result_Result_e8 core_convert_try_into_32_5e(int32_t self)
{
  return symcrust_ffi_try_from_2a(self);
}

#if defined(__cplusplus)
}
#endif

#define __internal_symcrust_ffi_H_DEFINED
#endif
