-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import Symcrust.Code.Types
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
open Symcrust

/- [symcrust::common::{core::cmp::PartialEq<symcrust::common::Error> for symcrust::common::Error}#1::ne]:
   Source: '/rustc/library/core/src/cmp.rs', lines 262:4-262:37 -/
axiom common.PartialEqsymcrustcommonErrorsymcrustcommonError.ne
  : common.Error → common.Error → Result Bool

/- [symcrust::common::SymCryptRandom]:
   Source: 'src/common.rs', lines 46:4-46:58 -/
axiom common.SymCryptRandom : MutRawPtr U8 → Usize → Result Unit

/- [symcrust::common::SymCryptModuleInit]:
   Source: 'src/common.rs', lines 47:4-47:48 -/
axiom common.SymCryptModuleInit : U32 → U32 → Result Unit

/- [symcrust::common::SymCryptWipe]:
   Source: 'src/common.rs', lines 48:4-48:54 -/
axiom common.SymCryptWipe : MutRawPtr U8 → Usize → Result Unit

/- [symcrust::common::random]:
   Source: 'src/common.rs', lines 51:0-61:1 -/
axiom common.random : Slice U8 → Result (common.Error × (Slice U8))

/- [symcrust::common::wipe_slice]:
   Source: 'src/common.rs', lines 76:0-78:1 -/
axiom common.wipe_slice {T : Type} : Slice T → Result (Slice T)

/- [symcrust::hash::shake128_extract]:
   Source: 'src/hash.rs', lines 146:0-150:1 -/
axiom hash.shake128_extract
  :
  hash.HashState → Slice U8 → Bool → Result (hash.HashState × (Slice
    U8))

/- [symcrust::key::{core::cmp::PartialEq<symcrust::key::Params> for symcrust::key::Params}#3::ne]:
   Source: '/rustc/library/core/src/cmp.rs', lines 262:4-262:37 -/
axiom key.PartialEqsymcrustkeyParamssymcrustkeyParams.ne
  : key.Params → key.Params → Result Bool

/- [symcrust::ntt::slice_to_sub_array]:
   Source: 'src/ntt.rs', lines 636:0-638:1 -/
axiom ntt.slice_to_sub_array
  (N : Usize) : Slice U8 → Usize → Result (Array U8 N)

