-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: type definitions
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

namespace Symcrust

/- Trait declaration: [core::marker::StructuralPartialEq]
   Source: '/rustc/library/core/src/marker.rs', lines 257:0-257:29
   Name pattern: [core::marker::StructuralPartialEq] -/
structure core.marker.StructuralPartialEq (Self : Type) where

/- [core::panicking::AssertKind]
   Source: '/rustc/library/core/src/panicking.rs', lines 382:0-382:19
   Name pattern: [core::panicking::AssertKind] -/
inductive core.panicking.AssertKind where
| Eq : core.panicking.AssertKind
| Ne : core.panicking.AssertKind
| Match : core.panicking.AssertKind

/- [symcrust::common::Error]
   Source: 'src/common.rs', lines 7:0-31:1 -/
inductive common.Error where
| NoError : common.Error
| Unused : common.Error
| WrongKeySize : common.Error
| WrongBlockSize : common.Error
| WrongDataSize : common.Error
| WrongNonceSize : common.Error
| WrongTagSize : common.Error
| WrongIterationCount : common.Error
| AuthenticationFailure : common.Error
| ExternalFailure : common.Error
| FipsFailure : common.Error
| HardwareFailure : common.Error
| NotImplemented : common.Error
| InvalidBlob : common.Error
| BufferTooSmall : common.Error
| InvalidArgument : common.Error
| MemoryAllocationFailure : common.Error
| SignatureVerificationFailure : common.Error
| IncompatibleFormat : common.Error
| ValueTooLarge : common.Error
| SessionReplayFailure : common.Error
| HbsNoOtsKeysLeft : common.Error
| HbsPublicRootMismatch : common.Error

/- [symcrust::hash::KeccakState]
   Source: 'src/hash.rs', lines 20:0-26:1 -/
structure hash.KeccakState where
  state : Array U64 25#usize
  input_block_size : U32
  state_index : U32
  padding_value : U8
  squeeze_mode : Bool

/- [symcrust::hash::HashState]
   Source: 'src/hash.rs', lines 30:0-33:1 -/
structure hash.HashState where
  ks : hash.KeccakState
  magic : Usize

/- [symcrust::key::Format]
   Source: 'src/key.rs', lines 15:0-28:1 -/
inductive key.Format where
| PrivateSeed : key.Format
| DecapsulationKey : key.Format
| EncapsulationKey : key.Format

/- [symcrust::key::Params]
   Source: 'src/key.rs', lines 31:0-37:1 -/
inductive key.Params where
| MlKem512 : key.Params
| MlKem768 : key.Params
| MlKem1024 : key.Params

/- [symcrust::key::InternalParams]
   Source: 'src/key.rs', lines 93:0-107:1 -/
structure key.InternalParams where
  params : key.Params
  n_rows : U8
  n_eta1 : U8
  n_eta2 : U8
  n_bits_of_u : U8
  n_bits_of_v : U8

/- [symcrust::key::PreKey2]
   Source: 'src/key.rs', lines 229:0-248:1 -/
structure key.PreKey2 (U : Type) where
  algorithm_info : U32
  params : key.InternalParams
  has_private_seed : Bool
  has_private_key : Bool
  private_seed : Array U8 32#usize
  private_random : Array U8 32#usize
  public_seed : Array U8 32#usize
  encoded_t : Array U8 1536#usize
  encaps_key_hash : Array U8 32#usize
  n_rows : Usize
  data : U

end Symcrust
