-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [symcrust]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas.Std Result Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- [core::fmt::Arguments]
   Source: '/rustc/library/core/src/fmt/mod.rs', lines 319:0-319:24
   Name pattern: core::fmt::Arguments -/
axiom core.fmt.Arguments : Type

/- [core::fmt::rt::Argument]
   Source: '/rustc/library/core/src/fmt/rt.rs', lines 92:0-92:23
   Name pattern: core::fmt::rt::Argument -/
axiom core.fmt.rt.Argument : Type

/- [alloc::collections::TryReserveError]
   Source: '/rustc/library/alloc/src/collections/mod.rs', lines 58:0-58:26
   Name pattern: alloc::collections::TryReserveError -/
axiom alloc.collections.TryReserveError : Type

